import { notFound } from "next/navigation";
import Link from "next/link";
import { getKnowledgeById } from "@/lib/db";

export const dynamic = "force-dynamic";

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const k = getKnowledgeById(id);
  if (!k) return { title: "Knowledge Not Found" };
  return {
    title: k.title.replace("[AI Synthesis] ", "") + " — CitePay Knowledge",
    description: k.description.slice(0, 160),
  };
}

export default async function KnowledgePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const k = getKnowledgeById(id);
  if (!k) notFound();

  const shortHash = k.contentHash.slice(0, 16) + "…";
  const priceUsdc = (k.price / 1_000_000).toFixed(4);
  const displayTitle = k.title.replace("[AI Synthesis] ", "");

  return (
    <main className="min-h-screen bg-[#0a0a0f] text-white">
      {/* Header */}
      <div className="border-b border-white/10 px-4 py-3 flex items-center gap-3">
        <Link href="/labs/orchestrate" className="text-white/40 hover:text-white/70 text-sm transition-colors">← Orchestrate</Link>
        <span className="text-white/20">|</span>
        <Link href="/market" className="text-white/40 hover:text-white/70 text-sm transition-colors">Market</Link>
        <span className="ml-auto flex items-center gap-2">
          <span className="px-2 py-0.5 rounded text-xs bg-violet-500/20 text-violet-300 border border-violet-500/30 font-mono">AI Synthesis</span>
          <span className="px-2 py-0.5 rounded text-xs bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">${priceUsdc} / citation</span>
        </span>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-12">
        {/* Badge row */}
        <div className="flex flex-wrap items-center gap-2 mb-6">
          <span className="px-3 py-1 rounded-full text-xs bg-violet-500/10 text-violet-300 border border-violet-500/20">
            AI-Synthesized Knowledge
          </span>
          <span className="px-3 py-1 rounded-full text-xs bg-white/5 text-white/50 font-mono">
            SHA-256: {shortHash}
          </span>
          <span className="px-3 py-1 rounded-full text-xs bg-white/5 text-white/50">
            {new Date(k.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
          </span>
          {k.paidCount > 0 && (
            <span className="px-3 py-1 rounded-full text-xs bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
              {k.paidCount} citation{k.paidCount !== 1 ? "s" : ""}
            </span>
          )}
        </div>

        {/* Title */}
        <h1 className="text-3xl font-bold text-white mb-4 leading-tight">{displayTitle}</h1>

        {/* Creator row */}
        <div className="flex items-center gap-3 mb-8 pb-8 border-b border-white/10">
          <div className="w-8 h-8 rounded-full bg-gradient-to-br from-violet-500 to-emerald-400 flex items-center justify-center text-xs font-bold">AI</div>
          <div>
            <p className="text-sm font-medium text-white/80">CitePay Orchestrator</p>
            <p className="text-xs text-white/40">@citepay_agent · Multi-agent synthesis</p>
          </div>
          <div className="ml-auto text-right">
            <p className="text-sm font-mono text-emerald-400">{priceUsdc} USDC</p>
            <p className="text-xs text-white/40">per citation</p>
          </div>
        </div>

        {/* Full content */}
        <div className="prose prose-invert prose-sm max-w-none">
          {k.fullContent.split("\n\n").map((para, i) => (
            <p key={i} className="text-white/80 leading-relaxed mb-4 text-base">
              {para}
            </p>
          ))}
        </div>

        {/* Integrity box */}
        <div className="mt-10 rounded-xl border border-white/10 bg-white/[0.03] p-6">
          <h3 className="text-sm font-semibold text-white/60 uppercase tracking-wider mb-4">Content Integrity</h3>
          <div className="grid gap-3 text-sm font-mono">
            <div className="flex justify-between gap-4">
              <span className="text-white/40">SHA-256</span>
              <span className="text-white/70 break-all text-right">{k.contentHash}</span>
            </div>
            <div className="flex justify-between gap-4">
              <span className="text-white/40">Source ID</span>
              <span className="text-white/70">{k.id}</span>
            </div>
            <div className="flex justify-between gap-4">
              <span className="text-white/40">Generated by</span>
              <span className="text-white/70">CitePay Multi-Agent Orchestrator</span>
            </div>
            <div className="flex justify-between gap-4">
              <span className="text-white/40">Network</span>
              <span className="text-white/70">Arc Testnet (chainId 5042002)</span>
            </div>
          </div>
        </div>

        {/* CTA */}
        <div className="mt-8 flex flex-col sm:flex-row gap-3">
          <a
            href={`/api/ask`}
            className="flex-1 text-center px-6 py-3 rounded-lg bg-gradient-to-r from-violet-600 to-indigo-600 text-white font-semibold hover:opacity-90 transition-opacity"
          >
            Cite this knowledge →
          </a>
          <Link
            href="/labs/orchestrate"
            className="flex-1 text-center px-6 py-3 rounded-lg border border-white/20 text-white/70 hover:text-white hover:border-white/40 transition-colors"
          >
            Generate new knowledge
          </Link>
          <Link
            href="/market"
            className="flex-1 text-center px-6 py-3 rounded-lg border border-white/20 text-white/70 hover:text-white hover:border-white/40 transition-colors"
          >
            Browse market
          </Link>
        </div>
      </div>
    </main>
  );
}
